#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later WITH AdditionRef-RazorFX-plugin-exception
# SPDX-FileCopyrightText: © 2026 Nitrofire Computing
"""Regenerate PARAMETERS.md from the effect / reactive schemas."""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
from razorfx.effects import EFFECTS
from razorfx.gui.app import REACTIVE_ADV


def rng(s):
    if s["type"] in ("float", "int"):
        return "%s \u2013 %s" % (s["min"], s["max"])
    if s["type"] == "choice":
        return " / ".join(s["choices"])
    return s["type"]


def table(schema):
    out = ["| Setting | Section | Default | Range | What it does |", "|---|---|---|---|---|"]
    for s in schema:
        d = s["default"]
        d = " \u2192 ".join(d) if isinstance(d, list) else d
        out.append("| %s | %s | %s | %s | %s |" % (s["label"], "Advanced" if s.get("adv") else "main", d, rng(s), s.get("help", "")))
    return "\n".join(out)


lines = ["# RazorFX: every adjustable setting", "",
         "Generated by `tools/gen_params_doc.py`. Everything here can be changed in the GUI; "
         "nothing needs code changes. \"Advanced\" settings are in the collapsible section under each panel.", ""]
for c in EFFECTS:
    lines += ["## %s" % c.name, "", "_Mimics: %s_" % c.mimics, "", table(c.schema()), ""]
lines += ["## Reactive layer (Advanced)", "", table(REACTIVE_ADV), ""]
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "PARAMETERS.md"), "w").write("\n".join(lines))
print("ok", sum(len(c.schema()) for c in EFFECTS) + len(REACTIVE_ADV), "settings")
