# SPDX-License-Identifier: GPL-3.0-or-later WITH AdditionRef-RGBMatrixFX-plugin-exception
# Installed by RGBMatrixFX to /etc/modules-load.d/ (install.sh) or /usr/lib/modules-load.d/ (packages):
# OpenRGB talks to motherboard and RAM lighting over SMBus/i2c, which needs the i2c-dev module.
# (The chipset SMBus driver, i2c-piix4 on AMD or i2c-i801 on Intel, loads automatically.)
i2c-dev
